'use client';

import { useEffect, useState } from 'react';
import { useBusiness } from '@/components/dashboard/DashboardProvider';
import { PageHelp } from '@/components/dashboard/PageHelp';

interface Payout {
  id: string;
  period_start: string;
  period_end: string;
  gross_commission: number;
  holdback: number;
  deductions: number;
  net_amount: number;
  currency: string;
  status: 'pending' | 'approved' | 'paid' | 'rejected';
  paid_at: string | null;
  notes: string | null;
  created_at: string;
}

const STATUS_STYLES: Record<string, { bg: string; text: string; label: string }> = {
  pending: { bg: 'bg-yellow-50 dark:bg-yellow-900/20', text: 'text-yellow-700 dark:text-yellow-400', label: 'Pending' },
  approved: { bg: 'bg-blue-50 dark:bg-blue-900/20', text: 'text-blue-700 dark:text-blue-400', label: 'Approved' },
  paid: { bg: 'bg-green-50 dark:bg-green-900/20', text: 'text-green-700 dark:text-green-400', label: 'Paid' },
  rejected: { bg: 'bg-red-50 dark:bg-red-900/20', text: 'text-red-700 dark:text-red-400', label: 'Rejected' },
};

export default function ResellerPayoutsPage() {
  const business = useBusiness();
  const [payouts, setPayouts] = useState<Payout[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);

  useEffect(() => {
    loadPayouts();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [business.id]);

  async function loadPayouts() {
    try {
      setError(false);
      const res = await fetch(`/api/reseller/payouts?business_id=${business.id}`);
      if (res.ok) {
        const data = await res.json();
        setPayouts(data.payouts || []);
      } else {
        setError(true);
      }
    } catch {
      setError(true);
    }
    setLoading(false);
  }

  function formatCurrency(amount: number) {
    return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(amount / 100);
  }

  function formatDate(dateStr: string) {
    return new Date(dateStr).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
  }

  // Summary calculations
  const totalEarned = payouts
    .filter((p) => p.status !== 'rejected')
    .reduce((sum, p) => sum + p.gross_commission, 0);

  const totalPaid = payouts
    .filter((p) => p.status === 'paid')
    .reduce((sum, p) => sum + p.net_amount, 0);

  const totalPending = payouts
    .filter((p) => p.status === 'pending' || p.status === 'approved')
    .reduce((sum, p) => sum + p.net_amount, 0);

  const pendingHoldbacks = payouts
    .filter((p) => p.status === 'pending' || p.status === 'approved')
    .reduce((sum, p) => sum + p.holdback, 0);

  const availableBalance = totalEarned - totalPaid - totalPending - pendingHoldbacks;

  if (loading) {
    return (
      <div className="flex min-h-[50vh] items-center justify-center">
        <div className="h-8 w-8 animate-spin rounded-full border-2 border-brand border-t-transparent" />
      </div>
    );
  }

  return (
    <div>
      <div>
        <h1 className="text-2xl font-bold text-gray-900 dark:text-gray-100">Payouts</h1>
        <p className="mt-1 text-sm text-gray-500 dark:text-gray-400">
          Track your commission payouts and available balance
        </p>
      </div>

      <PageHelp
        pageKey="reseller-payouts"
        title="Payouts"
        description="View your payout history and available balance. Payouts are generated by the admin team based on your earned commissions and are paid out after approval."
      />

      {error && (
        <div className="mt-4 rounded-lg border border-red-200 bg-red-50 dark:bg-red-900/20 dark:border-red-800 px-4 py-3 text-sm text-red-700 dark:text-red-400">
          Something went wrong loading data.{' '}
          <button onClick={() => { setError(false); setLoading(true); loadPayouts(); }} className="font-medium underline hover:no-underline">
            Try again
          </button>
        </div>
      )}

      {/* Summary Cards */}
      <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        {/* Total Earned */}
        <div className="rounded-xl border border-gray-100 dark:border-gray-700 bg-white dark:bg-gray-800 p-5">
          <div className="inline-flex rounded-lg bg-amber-50 dark:bg-amber-900/20 p-2 text-amber-600 dark:text-amber-400">
            <svg className="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M17 9V7a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2m2 4h10a2 2 0 002-2v-6a2 2 0 00-2-2H9a2 2 0 00-2 2v6a2 2 0 002 2zm7-5a2 2 0 11-4 0 2 2 0 014 0z" />
            </svg>
          </div>
          <p className="mt-3 text-lg font-bold text-gray-900 dark:text-gray-100">
            {formatCurrency(totalEarned)}
          </p>
          <p className="mt-1 text-xs text-gray-500 dark:text-gray-400">Total Earned</p>
        </div>

        {/* Total Paid */}
        <div className="rounded-xl border border-gray-100 dark:border-gray-700 bg-white dark:bg-gray-800 p-5">
          <div className="inline-flex rounded-lg bg-green-50 dark:bg-green-900/20 p-2 text-green-600 dark:text-green-400">
            <svg className="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
          </div>
          <p className="mt-3 text-lg font-bold text-gray-900 dark:text-gray-100">
            {formatCurrency(totalPaid)}
          </p>
          <p className="mt-1 text-xs text-gray-500 dark:text-gray-400">Total Paid</p>
        </div>

        {/* Pending */}
        <div className="rounded-xl border border-gray-100 dark:border-gray-700 bg-white dark:bg-gray-800 p-5">
          <div className="inline-flex rounded-lg bg-yellow-50 dark:bg-yellow-900/20 p-2 text-yellow-600 dark:text-yellow-400">
            <svg className="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
          </div>
          <p className="mt-3 text-lg font-bold text-gray-900 dark:text-gray-100">
            {formatCurrency(totalPending)}
          </p>
          <p className="mt-1 text-xs text-gray-500 dark:text-gray-400">Pending</p>
        </div>

        {/* Available Balance */}
        <div className="rounded-xl border border-gray-100 dark:border-gray-700 bg-white dark:bg-gray-800 p-5">
          <div className="inline-flex rounded-lg bg-blue-50 dark:bg-blue-900/20 p-2 text-blue-600 dark:text-blue-400">
            <svg className="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
          </div>
          <p className="mt-3 text-lg font-bold text-gray-900 dark:text-gray-100">
            {formatCurrency(Math.max(0, availableBalance))}
          </p>
          <p className="mt-1 text-xs text-gray-500 dark:text-gray-400">Available Balance</p>
        </div>
      </div>

      {/* Payout History */}
      <div className="mt-6">
        <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">Payout History</h2>

        {payouts.length === 0 ? (
          <div className="mt-4 rounded-xl border border-dashed border-gray-200 dark:border-gray-700 py-12 text-center">
            <svg className="mx-auto h-10 w-10 text-gray-300 dark:text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M17 9V7a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2m2 4h10a2 2 0 002-2v-6a2 2 0 00-2-2H9a2 2 0 00-2 2v6a2 2 0 002 2zm7-5a2 2 0 11-4 0 2 2 0 014 0z" />
            </svg>
            <p className="mt-3 text-sm text-gray-500 dark:text-gray-400">No payouts yet</p>
            <p className="mt-1 text-xs text-gray-400 dark:text-gray-500">
              Payouts will appear here once the admin team generates them based on your commissions
            </p>
          </div>
        ) : (
          <div className="mt-3 overflow-x-auto rounded-lg border border-gray-200 dark:border-gray-700">
            <table className="w-full text-sm">
              <thead className="border-b border-gray-100 dark:border-gray-700 bg-gray-50 dark:bg-gray-800">
                <tr>
                  <th scope="col" className="px-4 py-2.5 text-left text-xs font-medium text-gray-500 dark:text-gray-400">Period</th>
                  <th scope="col" className="px-4 py-2.5 text-right text-xs font-medium text-gray-500 dark:text-gray-400">Gross</th>
                  <th scope="col" className="px-4 py-2.5 text-right text-xs font-medium text-gray-500 dark:text-gray-400">Holdback</th>
                  <th scope="col" className="px-4 py-2.5 text-right text-xs font-medium text-gray-500 dark:text-gray-400">Deductions</th>
                  <th scope="col" className="px-4 py-2.5 text-right text-xs font-medium text-gray-500 dark:text-gray-400">Net</th>
                  <th scope="col" className="px-4 py-2.5 text-center text-xs font-medium text-gray-500 dark:text-gray-400">Status</th>
                  <th scope="col" className="px-4 py-2.5 text-left text-xs font-medium text-gray-500 dark:text-gray-400">Paid</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-50 dark:divide-gray-700">
                {payouts.map((payout) => {
                  const style = STATUS_STYLES[payout.status] || STATUS_STYLES.pending;
                  return (
                    <tr key={payout.id}>
                      <td className="px-4 py-2.5 text-gray-900 dark:text-gray-100 whitespace-nowrap">
                        {formatDate(payout.period_start)} - {formatDate(payout.period_end)}
                      </td>
                      <td className="px-4 py-2.5 text-right text-gray-700 dark:text-gray-300 whitespace-nowrap">
                        {formatCurrency(payout.gross_commission)}
                      </td>
                      <td className="px-4 py-2.5 text-right text-gray-500 dark:text-gray-400 whitespace-nowrap">
                        {payout.holdback > 0 ? `-${formatCurrency(payout.holdback)}` : '-'}
                      </td>
                      <td className="px-4 py-2.5 text-right text-gray-500 dark:text-gray-400 whitespace-nowrap">
                        {payout.deductions > 0 ? `-${formatCurrency(payout.deductions)}` : '-'}
                      </td>
                      <td className="px-4 py-2.5 text-right font-medium text-gray-900 dark:text-gray-100 whitespace-nowrap">
                        {formatCurrency(payout.net_amount)}
                      </td>
                      <td className="px-4 py-2.5 text-center whitespace-nowrap">
                        <span className={`inline-flex rounded-full px-2 py-0.5 text-xs font-medium ${style.bg} ${style.text}`}>
                          {style.label}
                        </span>
                      </td>
                      <td className="px-4 py-2.5 text-gray-500 dark:text-gray-400 whitespace-nowrap">
                        {payout.paid_at ? formatDate(payout.paid_at) : '-'}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
