import { NextResponse, type NextRequest } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { createServiceClient } from '@/lib/supabase/service';
import { initializePayment } from '@/lib/bot/flows/shared/payment';
import { ChannelResolver } from '@/lib/channels/channel-resolver';
import { rateLimitResponse, getRateLimitKey } from '@/lib/rate-limit';
import { formatCurrency, type CountryCode } from '@/lib/constants';
import { sendEmail } from '@/lib/email/client';
import { logger } from '@/lib/logger';

export async function POST(request: NextRequest) {
  try {
    const rateLimit = rateLimitResponse(getRateLimitKey(request, 'payment-request'), 20, 60_000);
    if (rateLimit) return rateLimit;

    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

    const { businessId, customerPhone, customerName, customerEmail, amount, description, sendVia = 'whatsapp' } = await request.json();

    // Validate based on delivery method
    if (!businessId || !amount) {
      return NextResponse.json({ error: 'businessId and amount are required' }, { status: 400 });
    }

    const effectiveSendVia: string = sendVia === 'auto'
      ? (customerEmail && customerEmail.includes('@') ? 'email' : 'whatsapp')
      : sendVia;

    if ((effectiveSendVia === 'whatsapp' || effectiveSendVia === 'both') && !customerPhone) {
      return NextResponse.json({ error: 'Phone number is required for WhatsApp delivery' }, { status: 400 });
    }
    if ((effectiveSendVia === 'email' || effectiveSendVia === 'both') && !customerEmail) {
      return NextResponse.json({ error: 'Email is required for email delivery' }, { status: 400 });
    }

    if (typeof amount !== 'number' || amount <= 0) {
      return NextResponse.json({ error: 'Amount must be a positive number' }, { status: 400 });
    }

    // Verify ownership
    const { data: biz } = await supabase
      .from('businesses')
      .select('id, name, country_code, payment_gateway')
      .eq('id', businessId)
      .eq('owner_id', user.id)
      .single();

    if (!biz) return NextResponse.json({ error: 'Forbidden' }, { status: 403 });

    const cc = (biz.country_code || 'NG') as CountryCode;
    const phone = customerPhone ? customerPhone.replace(/\D/g, '') : '';
    if ((effectiveSendVia === 'whatsapp' || effectiveSendVia === 'both') && (!phone || phone.length < 7)) {
      return NextResponse.json({ error: 'Invalid phone number' }, { status: 400 });
    }
    const email = customerEmail?.trim() || '';
    if ((effectiveSendVia === 'email' || effectiveSendVia === 'both') && email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      return NextResponse.json({ error: 'Invalid email address' }, { status: 400 });
    }

    const serviceClient = createServiceClient();

    // Create booking record for payment tracking
    // reference_code is auto-generated by the set_reference_code trigger (WA-PY-XXXX format)
    // date, time, party_size are NOT NULL on the bookings table — use placeholder values for payment-only records
    const today = new Date().toISOString().split('T')[0];
    const { data: booking, error: bookingError } = await serviceClient
      .from('bookings')
      .insert({
        business_id: businessId,
        user_id: user.id,
        guest_name: customerName || 'Customer',
        guest_phone: phone || email,
        total_amount: amount,
        status: 'confirmed',
        flow_type: 'payment',
        notes: description || null,
        date: today,
        time: '00:00',
        party_size: 1,
      })
      .select('id, reference_code')
      .single();

    if (bookingError || !booking) {
      logger.error('[PAYMENT-REQUEST] Failed to create booking:', bookingError);
      const detail = bookingError?.message || 'Unknown database error';
      return NextResponse.json({ error: `Failed to create payment record: ${detail}` }, { status: 500 });
    }

    const refCode = booking.reference_code;

    // Initialize payment
    const result = await initializePayment(serviceClient, {
      bookingId: booking.id,
      userId: user.id,
      amount,
      referenceCode: refCode,
      businessName: biz.name,
      phone,
      countryCode: cc,
      gatewayOverride: biz.payment_gateway,
      businessId: biz.id,
    });

    if (!result) {
      return NextResponse.json({ error: 'Failed to create payment link. Check that your payment gateway is configured correctly.' }, { status: 500 });
    }

    // Get direct gateway URL
    const { data: payment } = await serviceClient
      .from('payments')
      .select('gateway, gateway_reference, metadata')
      .eq('gateway_reference', result.reference)
      .eq('status', 'pending')
      .maybeSingle();

    let paymentUrl = result.url;
    if (payment?.gateway === 'paystack' && payment.gateway_reference) {
      paymentUrl = `https://checkout.paystack.com/${payment.gateway_reference}`;
    } else if (payment?.gateway === 'stripe') {
      const meta = (payment.metadata || {}) as Record<string, unknown>;
      const sessionId = meta.stripe_session_id as string;
      if (sessionId) {
        try {
          const key = process.env.STRIPE_SECRET_KEY || '';
          const res = await fetch(`https://api.stripe.com/v1/checkout/sessions/${sessionId}`, {
            headers: { Authorization: `Bearer ${key}` },
          });
          const session = await res.json();
          if (session.url) paymentUrl = session.url;
        } catch { /* use shortened URL */ }
      }
    }

    // Send WhatsApp message
    if (effectiveSendVia === 'whatsapp' || effectiveSendVia === 'both') {
      const resolver = new ChannelResolver(serviceClient);
      const resolved = await resolver.resolveByBusinessId(businessId);

      if (resolved) {
        const toPhone = phone.startsWith('+') ? phone.slice(1) : phone;
        const message = [
          `💳 *Payment Request*`,
          '',
          `from *${biz.name}*`,
          `💰 Amount: *${formatCurrency(amount, cc)}*`,
          description ? `📝 ${description}` : '',
          '',
          `Pay here 👇`,
          paymentUrl,
        ].filter(Boolean).join('\n');

        try {
          await resolved.sender.sendText({ to: toPhone, text: message });
        } catch (sendErr) {
          logger.error('[PAYMENT-REQUEST] WhatsApp send failed:', sendErr);
        }
      }
    }

    // Send email
    if ((effectiveSendVia === 'email' || effectiveSendVia === 'both') && email) {
      await sendEmail({
        to: email,
        subject: `Payment Request from ${biz.name} — ${formatCurrency(amount, cc)}`,
        html: `
          <div style="font-family: sans-serif; max-width: 480px; margin: 0 auto;">
            <h2 style="color: #333;">Payment Request</h2>
            <p>from <strong>${biz.name}</strong></p>
            <div style="background: #f9f9f9; border-radius: 8px; padding: 20px; margin: 20px 0;">
              <p style="font-size: 24px; font-weight: bold; color: #333; margin: 0;">${formatCurrency(amount, cc)}</p>
              ${description ? `<p style="color: #666; margin-top: 8px;">${description}</p>` : ''}
            </div>
            <a href="${paymentUrl}" style="display: inline-block; background: #6C2BD9; color: white; padding: 12px 24px; border-radius: 8px; text-decoration: none; font-weight: bold;">Pay Now</a>
            <p style="color: #999; font-size: 12px; margin-top: 24px;">Powered by Waaiio</p>
          </div>
        `,
      }).catch(err => logger.error('[PAYMENT-REQUEST] Email error:', err));
    }

    return NextResponse.json({
      success: true,
      paymentUrl,
      reference: refCode,
    });
  } catch (error) {
    logger.error('[PAYMENT-REQUEST] Error:', error);
    return NextResponse.json({ error: 'Something went wrong. Please try again.' }, { status: 500 });
  }
}
