-- 235: Add quantity validation to catalog order RPC
-- Prevents negative/zero quantities, excessive item counts, and oversized orders.

CREATE OR REPLACE FUNCTION create_catalog_order_atomic(
  p_business_id UUID,
  p_user_id UUID,
  p_delivery_phone TEXT,
  p_meta_message_id TEXT,
  p_customer_note TEXT,
  p_items JSONB -- array of {product_id, quantity}
) RETURNS JSONB AS $$
DECLARE
  v_order_id UUID;
  v_item JSONB;
  v_product RECORD;
  v_total_amount BIGINT := 0;
  v_order_items JSONB := '[]'::JSONB;
  v_out_of_stock TEXT[] := '{}';
  v_valid_count INT := 0;
BEGIN
  -- Validate items array
  IF p_items IS NULL OR jsonb_array_length(p_items) = 0 THEN
    RETURN jsonb_build_object('success', false, 'reason', 'no_items');
  END IF;
  IF jsonb_array_length(p_items) > 50 THEN
    RETURN jsonb_build_object('success', false, 'reason', 'too_many_items');
  END IF;

  -- 1. Check dedup via processed_webhook_events
  IF EXISTS (SELECT 1 FROM processed_webhook_events WHERE event_id = 'meta-order-' || p_meta_message_id) THEN
    RETURN jsonb_build_object('success', false, 'reason', 'duplicate', 'order_id', NULL);
  END IF;

  -- 2. Process each item
  FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
  LOOP
    -- Validate quantity is a positive integer within bounds
    IF (v_item->>'quantity')::INT IS NULL OR (v_item->>'quantity')::INT < 1 THEN
      RAISE EXCEPTION 'Invalid quantity for product %: must be a positive integer', v_item->>'product_id';
    END IF;
    IF (v_item->>'quantity')::INT > 100 THEN
      RAISE EXCEPTION 'Quantity exceeds maximum (100) for product %', v_item->>'product_id';
    END IF;

    -- Lock the product row for update
    SELECT id, name, price, stock_quantity, track_inventory, is_active, business_id
    INTO v_product
    FROM products
    WHERE id = (v_item->>'product_id')::UUID
    FOR UPDATE;

    -- Validate product exists
    IF v_product IS NULL THEN
      CONTINUE; -- skip unknown products (Meta may send stale catalog items)
    END IF;

    -- Validate product belongs to business
    IF v_product.business_id != p_business_id THEN
      CONTINUE;
    END IF;

    -- Validate product is active
    IF NOT v_product.is_active THEN
      CONTINUE;
    END IF;

    -- Check inventory
    IF v_product.track_inventory AND v_product.stock_quantity IS NOT NULL THEN
      IF v_product.stock_quantity < (v_item->>'quantity')::INT THEN
        v_out_of_stock := array_append(v_out_of_stock, v_product.name);
        CONTINUE;
      END IF;
      -- Decrement inventory atomically
      UPDATE products SET stock_quantity = stock_quantity - (v_item->>'quantity')::INT
      WHERE id = v_product.id;
    END IF;

    -- Accumulate total using DB-authoritative price (NOT webhook price)
    v_total_amount := v_total_amount + (v_product.price * (v_item->>'quantity')::INT);
    v_valid_count := v_valid_count + 1;

    -- Build order item record
    v_order_items := v_order_items || jsonb_build_object(
      'product_id', v_product.id,
      'product_name', v_product.name,
      'quantity', (v_item->>'quantity')::INT,
      'unit_price', v_product.price
    );
  END LOOP;

  -- If no valid items, return without creating order
  IF v_valid_count = 0 THEN
    RETURN jsonb_build_object(
      'success', false,
      'reason', 'no_valid_items',
      'out_of_stock', to_jsonb(v_out_of_stock)
    );
  END IF;

  -- 3. Create order (reference_code auto-generated by trigger)
  INSERT INTO orders (
    business_id, user_id, status, delivery_phone, total_amount, channel, notes
  ) VALUES (
    p_business_id,
    p_user_id,
    CASE WHEN v_total_amount > 0 THEN 'pending'::order_status ELSE 'confirmed'::order_status END,
    p_delivery_phone,
    v_total_amount,
    'whatsapp',
    NULLIF(p_customer_note, '')
  )
  RETURNING id INTO v_order_id;

  -- 4. Create order items
  INSERT INTO order_items (order_id, product_id, quantity, unit_price)
  SELECT
    v_order_id,
    (item->>'product_id')::UUID,
    (item->>'quantity')::INT,
    (item->>'unit_price')::INT
  FROM jsonb_array_elements(v_order_items) AS item;

  -- 5. Record dedup event
  INSERT INTO processed_webhook_events (event_id, gateway, event_type, processed_at)
  VALUES ('meta-order-' || p_meta_message_id, 'meta_cloud', 'catalog_order', NOW());

  -- 6. Fetch the generated reference_code
  RETURN jsonb_build_object(
    'success', true,
    'order_id', v_order_id,
    'reference_code', (SELECT reference_code FROM orders WHERE id = v_order_id),
    'total_amount', v_total_amount,
    'items', v_order_items,
    'out_of_stock', to_jsonb(v_out_of_stock)
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public;
