-- B25 ACL Rollback Script
-- Generated: 2026-09-25
-- Exact inverse of B25_acl_repair.sql (full Supabase default ACL baseline)

BEGIN;

-- ==============================================================
-- INVERSE PART 1: REVOKE DEFAULT PRIVILEGES
-- ==============================================================

-- postgres role — revoke full Supabase baseline: anon, authenticated, service_role
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public REVOKE ALL ON TABLES FROM anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public REVOKE ALL ON SEQUENCES FROM anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public REVOKE EXECUTE ON FUNCTIONS FROM anon, authenticated, service_role;

-- supabase_admin role — revoke full Supabase baseline: anon, authenticated, service_role
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public REVOKE ALL ON TABLES FROM anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public REVOKE ALL ON SEQUENCES FROM anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public REVOKE EXECUTE ON FUNCTIONS FROM anon, authenticated, service_role;

-- ==============================================================
-- INVERSE PART 2: REVOKE TABLE GRANTS
-- ==============================================================

-- Re-GRANT what repair revoked (restore pre-repair state)
GRANT SELECT ON TABLE public.businesses_public TO anon;
GRANT SELECT ON TABLE public.businesses_public TO authenticated;
GRANT SELECT ON TABLE public.whatsapp_channels_public TO anon;
GRANT SELECT ON TABLE public.whatsapp_channels_public TO authenticated;

-- REVOKE ALL ON ... FROM anon
REVOKE ALL ON public.admin_audit_logs, public.admin_broadcasts, public.admin_impersonation_tokens, public.admin_role_permissions, public.ai_classification_log, public.ai_conversation_config, public.ai_usage, public.alerts, public.api_keys, public.appointments FROM anon;
REVOKE ALL ON public.attendance_log, public.audit_log, public.blocked_phones, public.booking_confirmation_intents, public.booking_slots, public.bookings, public.bot_rules, public.bot_sequence_enrollments, public.bot_sequence_steps, public.bot_sequences FROM anon;
REVOKE ALL ON public.bot_sessions, public.bot_step_overrides, public.broadcast_usage, public.business_bank_accounts, public.business_broadcasts, public.business_capabilities, public.business_documents, public.business_faq, public.business_locations, public.business_members FROM anon;
REVOKE ALL ON public.business_payouts, public.business_staff, public.campaign_donations, public.campaigns, public.canned_responses, public.capability_overrides, public.catalog_sync_logs, public.category_definitions, public.category_templates, public.chat_conversations FROM anon;
REVOKE ALL ON public.chat_forward_usage, public.chat_messages, public.contract_signers, public.contract_templates, public.contracts, public.conversation_usage, public.countries, public.customer_consents, public.customer_feedback, public.customer_profiles FROM anon;
REVOKE ALL ON public.customer_reports, public.customer_subscriptions, public.daily_summary_log, public.delivery_zones, public.demo_requests, public.event_invites, public.event_ticket_types, public.event_tickets, public.events, public.flow_dropoffs FROM anon;
REVOKE ALL ON public.flow_execution_aggregates, public.flow_execution_summaries, public.form_responses, public.forms, public.fraud_events, public.growth_campaign_recipients, public.growth_campaigns, public.growth_contacts, public.growth_credit_transactions, public.growth_credits FROM anon;
REVOKE ALL ON public.growth_imports, public.growth_pricing, public.impersonation_logs, public.invoice_items, public.invoice_payment_applications, public.invoices, public.keyword_campaign_responses, public.keyword_campaigns, public.launch_delivery_confirmations, public.launch_subscribers FROM anon;
REVOKE ALL ON public.llm_classifications, public.loyalty_points, public.loyalty_transactions, public.membership_tiers, public.message_send_attempts, public.messaging_opt_outs, public.messaging_suspension_audit, public.notifications, public.order_items, public.order_spend_applications FROM anon;
REVOKE ALL ON public.order_stock_applications, public.order_tracking_notifications, public.orders, public.package_enrollments, public.package_redemptions, public.parties, public.payment_confirmation_deliveries, public.payment_links, public.payment_spend_applications, public.payments FROM anon;
REVOKE ALL ON public.payout_accounts, public.payout_adjustments, public.payout_terms_acceptance, public.paystack_billing_attempts, public.pending_transfers, public.platform_config_versions, public.platform_fee_invoices, public.platform_fees, public.platform_settings, public.poll_votes FROM anon;
REVOKE ALL ON public.polls, public.product_addons, public.product_variants, public.products, public.promo_campaign_codes, public.promo_campaigns, public.promo_code_batches, public.promo_codes, public.promo_eligibility_acks, public.promo_fulfillment_notification_intents FROM anon;
REVOKE ALL ON public.promo_pending_eligibility, public.promo_pickup_verifications, public.promo_prizes, public.promo_redemptions, public.promo_reservations, public.promo_verification_attempts, public.promo_winner_contacts, public.properties, public.property_blocked_dates, public.queue_entries FROM anon;
REVOKE ALL ON public.queue_reopen_subscriptions, public.quote_requests, public.recurring_setup_intents, public.referrals, public.refund_requests, public.reseller_invoices, public.reseller_payouts, public.resellers, public.reservations, public.saved_payment_methods FROM anon;
REVOKE ALL ON public.security_events, public.security_sessions, public.service_addons, public.service_packages, public.services, public.signed_waivers, public.site_pages, public.stripe_recurring_finalizations, public.subscription_charges, public.subscription_checkout_intents FROM anon;
REVOKE ALL ON public.subscription_payment_quarantine, public.subscription_payments, public.subscriptions, public.support_ticket_messages, public.support_tickets, public.survey_responses, public.surveys, public.unmatched_delivery_statuses, public.verification_requests, public.volume_discount_rules FROM anon;
REVOKE ALL ON public.waitlist_entries, public.waiver_templates, public.webhook_deliveries, public.webhook_endpoints, public.whatsapp_config FROM anon;

-- REVOKE ALL ON ... FROM authenticated
REVOKE ALL ON public.admin_audit_logs, public.admin_broadcasts, public.admin_impersonation_tokens, public.admin_role_permissions, public.ai_classification_log, public.ai_conversation_config, public.ai_usage, public.alerts, public.api_keys, public.appointments FROM authenticated;
REVOKE ALL ON public.attendance_log, public.audit_log, public.blocked_phones, public.booking_confirmation_intents, public.booking_slots, public.bookings, public.bot_keywords, public.bot_rules, public.bot_sequence_enrollments, public.bot_sequence_steps FROM authenticated;
REVOKE ALL ON public.bot_sequences, public.bot_sessions, public.bot_step_overrides, public.broadcast_usage, public.business_bank_accounts, public.business_broadcasts, public.business_capabilities, public.business_documents, public.business_faq, public.business_locations FROM authenticated;
REVOKE ALL ON public.business_members, public.business_payouts, public.business_staff, public.businesses, public.campaign_donations, public.campaigns, public.canned_responses, public.capability_overrides, public.catalog_sync_logs, public.category_definitions FROM authenticated;
REVOKE ALL ON public.category_templates, public.chat_conversations, public.chat_forward_usage, public.chat_messages, public.contract_signers, public.contract_templates, public.contracts, public.conversation_usage, public.countries, public.customer_consents FROM authenticated;
REVOKE ALL ON public.customer_feedback, public.customer_profiles, public.customer_reports, public.customer_subscriptions, public.daily_summary_log, public.delivery_zones, public.demo_requests, public.event_invites, public.event_ticket_types, public.event_tickets FROM authenticated;
REVOKE ALL ON public.events, public.flow_dropoffs, public.flow_execution_aggregates, public.flow_execution_summaries, public.form_responses, public.forms, public.fraud_events, public.growth_campaign_recipients, public.growth_campaigns, public.growth_contacts FROM authenticated;
REVOKE ALL ON public.growth_credit_transactions, public.growth_credits, public.growth_imports, public.growth_pricing, public.impersonation_logs, public.invoice_items, public.invoice_payment_applications, public.invoices, public.keyword_campaign_responses, public.keyword_campaigns FROM authenticated;
REVOKE ALL ON public.launch_delivery_confirmations, public.launch_subscribers, public.llm_classifications, public.loyalty_points, public.loyalty_transactions, public.membership_tiers, public.message_send_attempts, public.messaging_opt_outs, public.messaging_suspension_audit, public.notifications FROM authenticated;
REVOKE ALL ON public.order_items, public.order_spend_applications, public.order_stock_applications, public.order_tracking_notifications, public.orders, public.package_enrollments, public.package_redemptions, public.parties, public.payment_confirmation_deliveries, public.payment_links FROM authenticated;
REVOKE ALL ON public.payment_spend_applications, public.payments, public.payout_accounts, public.payout_adjustments, public.payout_terms_acceptance, public.paystack_billing_attempts, public.pending_transfers, public.platform_config_versions, public.platform_fee_invoices, public.platform_fees FROM authenticated;
REVOKE ALL ON public.platform_settings, public.poll_votes, public.polls, public.product_addons, public.product_variants, public.products, public.promo_campaign_codes, public.promo_campaigns, public.promo_code_batches, public.promo_codes FROM authenticated;
REVOKE ALL ON public.promo_eligibility_acks, public.promo_fulfillment_notification_intents, public.promo_pending_eligibility, public.promo_pickup_verifications, public.promo_prizes, public.promo_redemptions, public.promo_reservations, public.promo_verification_attempts, public.promo_winner_contacts, public.properties FROM authenticated;
REVOKE ALL ON public.property_blocked_dates, public.queue_entries, public.queue_reopen_subscriptions, public.quote_requests, public.recurring_setup_intents, public.referrals, public.refund_requests, public.refunds, public.reseller_invoices, public.reseller_payouts FROM authenticated;
REVOKE ALL ON public.resellers, public.reservations, public.saved_payment_methods, public.security_events, public.security_sessions, public.service_addons, public.service_packages, public.services, public.signed_waivers, public.site_pages FROM authenticated;
REVOKE ALL ON public.stripe_recurring_finalizations, public.subscription_charges, public.subscription_checkout_intents, public.subscription_payment_quarantine, public.subscription_payments, public.subscriptions, public.support_ticket_messages, public.support_tickets, public.survey_responses, public.surveys FROM authenticated;
REVOKE ALL ON public.unmatched_delivery_statuses, public.verification_requests, public.volume_discount_rules, public.waitlist_entries, public.waiver_templates, public.webhook_deliveries, public.webhook_endpoints, public.whatsapp_channels, public.whatsapp_config FROM authenticated;

-- REVOKE ALL ON ... FROM service_role
REVOKE ALL ON public.admin_audit_logs, public.admin_broadcasts, public.admin_impersonation_tokens, public.admin_role_permissions, public.ai_classification_log, public.ai_conversation_config, public.ai_usage, public.alerts, public.api_keys, public.appointments FROM service_role;
REVOKE ALL ON public.attendance_log, public.audit_log, public.blocked_phones, public.booking_confirmation_intents, public.booking_slots, public.bookings, public.bot_keywords, public.bot_rules, public.bot_sequence_enrollments, public.bot_sequence_steps FROM service_role;
REVOKE ALL ON public.bot_sequences, public.bot_sessions, public.bot_step_overrides, public.broadcast_usage, public.business_bank_accounts, public.business_broadcasts, public.business_capabilities, public.business_documents, public.business_faq, public.business_locations FROM service_role;
REVOKE ALL ON public.business_members, public.business_payouts, public.business_staff, public.campaign_donations, public.campaigns, public.canned_responses, public.capability_overrides, public.catalog_sync_logs, public.category_definitions, public.category_templates FROM service_role;
REVOKE ALL ON public.chat_conversations, public.chat_forward_usage, public.chat_messages, public.contract_signers, public.contract_templates, public.contracts, public.conversation_usage, public.countries, public.customer_consents, public.customer_feedback FROM service_role;
REVOKE ALL ON public.customer_profiles, public.customer_reports, public.customer_subscriptions, public.daily_summary_log, public.delivery_zones, public.demo_requests, public.event_invites, public.event_ticket_types, public.event_tickets, public.events FROM service_role;
REVOKE ALL ON public.flow_dropoffs, public.flow_execution_aggregates, public.flow_execution_summaries, public.form_responses, public.forms, public.fraud_events, public.growth_campaign_recipients, public.growth_campaigns, public.growth_contacts, public.growth_credit_transactions FROM service_role;
REVOKE ALL ON public.growth_credits, public.growth_imports, public.growth_pricing, public.impersonation_logs, public.invoice_items, public.invoice_payment_applications, public.invoices, public.keyword_campaign_responses, public.keyword_campaigns, public.launch_delivery_confirmations FROM service_role;
REVOKE ALL ON public.launch_subscribers, public.llm_classifications, public.loyalty_points, public.loyalty_transactions, public.membership_tiers, public.message_send_attempts, public.messaging_opt_outs, public.messaging_suspension_audit, public.notifications, public.order_items FROM service_role;
REVOKE ALL ON public.order_spend_applications, public.order_stock_applications, public.order_tracking_notifications, public.orders, public.package_enrollments, public.package_redemptions, public.parties, public.payment_confirmation_deliveries, public.payment_links, public.payment_spend_applications FROM service_role;
REVOKE ALL ON public.payment_visit_applications, public.payments, public.payout_accounts, public.payout_adjustments, public.payout_terms_acceptance, public.paystack_billing_attempts, public.pending_transfers, public.platform_config_versions, public.platform_fee_invoices, public.platform_fees FROM service_role;
REVOKE ALL ON public.platform_settings, public.poll_votes, public.polls, public.processed_webhook_events, public.product_addons, public.product_variants, public.products, public.promo_campaign_codes, public.promo_campaigns, public.promo_code_batches FROM service_role;
REVOKE ALL ON public.promo_codes, public.promo_eligibility_acks, public.promo_fulfillment_notification_intents, public.promo_pending_eligibility, public.promo_prizes, public.promo_redemptions, public.promo_reservations, public.promo_verification_attempts, public.promo_winner_contacts, public.properties FROM service_role;
REVOKE ALL ON public.property_blocked_dates, public.provider_cleanup_operations, public.provider_customer_identities, public.queue_entries, public.queue_reopen_subscriptions, public.quote_requests, public.recurring_setup_intents, public.referrals, public.refund_requests, public.reseller_invoices FROM service_role;
REVOKE ALL ON public.reseller_payouts, public.resellers, public.reservations, public.saved_card_auth_attempts, public.saved_payment_methods, public.security_events, public.security_sessions, public.service_addons, public.service_packages, public.services FROM service_role;
REVOKE ALL ON public.signed_waivers, public.site_pages, public.stripe_recurring_finalizations, public.subscription_charges, public.subscription_checkout_intents, public.subscription_payment_quarantine, public.subscription_payments, public.subscriptions, public.support_ticket_messages, public.support_tickets FROM service_role;
REVOKE ALL ON public.survey_responses, public.surveys, public.unmatched_delivery_statuses, public.verification_requests, public.volume_discount_rules, public.waitlist_entries, public.waiver_templates, public.webhook_deliveries, public.webhook_endpoints, public.whatsapp_channels FROM service_role;
REVOKE ALL ON public.whatsapp_config FROM service_role;

-- ==============================================================
-- INVERSE PART 3: REVOKE ROUTINE EXECUTE GRANTS
-- ==============================================================

REVOKE EXECUTE ON FUNCTION public.calculate_volume_discount(p_business_id uuid, p_product_id uuid, p_quantity integer, p_unit_price integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.calculate_volume_discount(p_business_id uuid, p_product_id uuid, p_quantity integer, p_unit_price integer) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.calculate_volume_discount(p_business_id uuid, p_product_id uuid, p_quantity integer, p_unit_price integer) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.cash_dist(money, money) FROM anon;
REVOKE EXECUTE ON FUNCTION public.cash_dist(money, money) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.cash_dist(money, money) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.check_business_role(p_user_id uuid, p_business_id uuid, p_required_roles business_role[]) FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_business_role(p_user_id uuid, p_business_id uuid, p_required_roles business_role[]) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.check_business_role(p_user_id uuid, p_business_id uuid, p_required_roles business_role[]) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.check_conversation_limit(p_business_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_conversation_limit(p_business_id uuid) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.check_conversation_limit(p_business_id uuid) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.claim_launch_delivery(p_subscriber_id uuid, p_campaign_version text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.claim_launch_delivery(p_subscriber_id uuid, p_campaign_version text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.claim_launch_delivery(p_subscriber_id uuid, p_campaign_version text) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.complete_launch_delivery(p_subscriber_id uuid, p_claim_token uuid, p_status text, p_message_id text, p_error text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.complete_launch_delivery(p_subscriber_id uuid, p_claim_token uuid, p_status text, p_message_id text, p_error text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.complete_launch_delivery(p_subscriber_id uuid, p_claim_token uuid, p_status text, p_message_id text, p_error text) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.consume_launch_confirmation(p_token uuid, p_admin_id uuid, p_campaign_version text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.consume_launch_confirmation(p_token uuid, p_admin_id uuid, p_campaign_version text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.consume_launch_confirmation(p_token uuid, p_admin_id uuid, p_campaign_version text) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.consume_launch_confirmation(p_token uuid, p_admin_id uuid, p_campaign_version text, p_retry_only boolean, p_send_limit integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.consume_launch_confirmation(p_token uuid, p_admin_id uuid, p_campaign_version text, p_retry_only boolean, p_send_limit integer) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.consume_launch_confirmation(p_token uuid, p_admin_id uuid, p_campaign_version text, p_retry_only boolean, p_send_limit integer) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.date_dist(date, date) FROM anon;
REVOKE EXECUTE ON FUNCTION public.date_dist(date, date) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.date_dist(date, date) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.enforce_attempt_status_transitions() FROM anon;
REVOKE EXECUTE ON FUNCTION public.enforce_attempt_status_transitions() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.enforce_attempt_status_transitions() FROM service_role;
REVOKE EXECUTE ON FUNCTION public.enforce_disposition_transitions() FROM anon;
REVOKE EXECUTE ON FUNCTION public.enforce_disposition_transitions() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.enforce_disposition_transitions() FROM service_role;
REVOKE EXECUTE ON FUNCTION public.enforce_spend_period_provenance_immutability() FROM anon;
REVOKE EXECUTE ON FUNCTION public.enforce_spend_period_provenance_immutability() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.enforce_spend_period_provenance_immutability() FROM service_role;
REVOKE EXECUTE ON FUNCTION public.enforce_wamid_immutability() FROM anon;
REVOKE EXECUTE ON FUNCTION public.enforce_wamid_immutability() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.enforce_wamid_immutability() FROM service_role;
REVOKE EXECUTE ON FUNCTION public.float4_dist(real, real) FROM anon;
REVOKE EXECUTE ON FUNCTION public.float4_dist(real, real) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.float4_dist(real, real) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.float8_dist(double precision, double precision) FROM anon;
REVOKE EXECUTE ON FUNCTION public.float8_dist(double precision, double precision) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.float8_dist(double precision, double precision) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_bit_compress(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_bit_compress(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_bit_compress(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_bit_consistent(internal, bit, smallint, oid, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_bit_consistent(internal, bit, smallint, oid, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_bit_consistent(internal, bit, smallint, oid, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_bit_penalty(internal, internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_bit_penalty(internal, internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_bit_penalty(internal, internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_bit_picksplit(internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_bit_picksplit(internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_bit_picksplit(internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_bit_same(gbtreekey_var, gbtreekey_var, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_bit_same(gbtreekey_var, gbtreekey_var, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_bit_same(gbtreekey_var, gbtreekey_var, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_bit_union(internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_bit_union(internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_bit_union(internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_bool_compress(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_bool_compress(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_bool_compress(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_bool_consistent(internal, boolean, smallint, oid, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_bool_consistent(internal, boolean, smallint, oid, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_bool_consistent(internal, boolean, smallint, oid, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_bool_fetch(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_bool_fetch(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_bool_fetch(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_bool_penalty(internal, internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_bool_penalty(internal, internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_bool_penalty(internal, internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_bool_picksplit(internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_bool_picksplit(internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_bool_picksplit(internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_bool_same(gbtreekey2, gbtreekey2, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_bool_same(gbtreekey2, gbtreekey2, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_bool_same(gbtreekey2, gbtreekey2, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_bool_union(internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_bool_union(internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_bool_union(internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_bpchar_compress(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_bpchar_compress(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_bpchar_compress(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_bpchar_consistent(internal, character, smallint, oid, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_bpchar_consistent(internal, character, smallint, oid, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_bpchar_consistent(internal, character, smallint, oid, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_bytea_compress(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_bytea_compress(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_bytea_compress(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_bytea_consistent(internal, bytea, smallint, oid, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_bytea_consistent(internal, bytea, smallint, oid, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_bytea_consistent(internal, bytea, smallint, oid, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_bytea_penalty(internal, internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_bytea_penalty(internal, internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_bytea_penalty(internal, internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_bytea_picksplit(internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_bytea_picksplit(internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_bytea_picksplit(internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_bytea_same(gbtreekey_var, gbtreekey_var, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_bytea_same(gbtreekey_var, gbtreekey_var, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_bytea_same(gbtreekey_var, gbtreekey_var, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_bytea_union(internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_bytea_union(internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_bytea_union(internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_cash_compress(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_cash_compress(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_cash_compress(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_cash_consistent(internal, money, smallint, oid, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_cash_consistent(internal, money, smallint, oid, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_cash_consistent(internal, money, smallint, oid, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_cash_distance(internal, money, smallint, oid, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_cash_distance(internal, money, smallint, oid, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_cash_distance(internal, money, smallint, oid, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_cash_fetch(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_cash_fetch(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_cash_fetch(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_cash_penalty(internal, internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_cash_penalty(internal, internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_cash_penalty(internal, internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_cash_picksplit(internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_cash_picksplit(internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_cash_picksplit(internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_cash_same(gbtreekey16, gbtreekey16, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_cash_same(gbtreekey16, gbtreekey16, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_cash_same(gbtreekey16, gbtreekey16, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_cash_union(internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_cash_union(internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_cash_union(internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_date_compress(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_date_compress(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_date_compress(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_date_consistent(internal, date, smallint, oid, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_date_consistent(internal, date, smallint, oid, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_date_consistent(internal, date, smallint, oid, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_date_distance(internal, date, smallint, oid, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_date_distance(internal, date, smallint, oid, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_date_distance(internal, date, smallint, oid, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_date_fetch(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_date_fetch(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_date_fetch(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_date_penalty(internal, internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_date_penalty(internal, internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_date_penalty(internal, internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_date_picksplit(internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_date_picksplit(internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_date_picksplit(internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_date_same(gbtreekey8, gbtreekey8, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_date_same(gbtreekey8, gbtreekey8, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_date_same(gbtreekey8, gbtreekey8, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_date_union(internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_date_union(internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_date_union(internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_decompress(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_decompress(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_decompress(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_enum_compress(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_enum_compress(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_enum_compress(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_enum_consistent(internal, anyenum, smallint, oid, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_enum_consistent(internal, anyenum, smallint, oid, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_enum_consistent(internal, anyenum, smallint, oid, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_enum_fetch(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_enum_fetch(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_enum_fetch(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_enum_penalty(internal, internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_enum_penalty(internal, internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_enum_penalty(internal, internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_enum_picksplit(internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_enum_picksplit(internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_enum_picksplit(internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_enum_same(gbtreekey8, gbtreekey8, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_enum_same(gbtreekey8, gbtreekey8, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_enum_same(gbtreekey8, gbtreekey8, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_enum_union(internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_enum_union(internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_enum_union(internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_float4_compress(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_float4_compress(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_float4_compress(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_float4_consistent(internal, real, smallint, oid, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_float4_consistent(internal, real, smallint, oid, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_float4_consistent(internal, real, smallint, oid, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_float4_distance(internal, real, smallint, oid, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_float4_distance(internal, real, smallint, oid, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_float4_distance(internal, real, smallint, oid, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_float4_fetch(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_float4_fetch(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_float4_fetch(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_float4_penalty(internal, internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_float4_penalty(internal, internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_float4_penalty(internal, internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_float4_picksplit(internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_float4_picksplit(internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_float4_picksplit(internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_float4_same(gbtreekey8, gbtreekey8, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_float4_same(gbtreekey8, gbtreekey8, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_float4_same(gbtreekey8, gbtreekey8, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_float4_union(internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_float4_union(internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_float4_union(internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_float8_compress(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_float8_compress(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_float8_compress(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_float8_consistent(internal, double precision, smallint, oid, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_float8_consistent(internal, double precision, smallint, oid, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_float8_consistent(internal, double precision, smallint, oid, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_float8_distance(internal, double precision, smallint, oid, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_float8_distance(internal, double precision, smallint, oid, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_float8_distance(internal, double precision, smallint, oid, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_float8_fetch(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_float8_fetch(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_float8_fetch(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_float8_penalty(internal, internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_float8_penalty(internal, internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_float8_penalty(internal, internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_float8_picksplit(internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_float8_picksplit(internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_float8_picksplit(internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_float8_same(gbtreekey16, gbtreekey16, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_float8_same(gbtreekey16, gbtreekey16, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_float8_same(gbtreekey16, gbtreekey16, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_float8_union(internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_float8_union(internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_float8_union(internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_inet_compress(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_inet_compress(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_inet_compress(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_inet_consistent(internal, inet, smallint, oid, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_inet_consistent(internal, inet, smallint, oid, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_inet_consistent(internal, inet, smallint, oid, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_inet_penalty(internal, internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_inet_penalty(internal, internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_inet_penalty(internal, internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_inet_picksplit(internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_inet_picksplit(internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_inet_picksplit(internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_inet_same(gbtreekey16, gbtreekey16, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_inet_same(gbtreekey16, gbtreekey16, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_inet_same(gbtreekey16, gbtreekey16, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_inet_union(internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_inet_union(internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_inet_union(internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_int2_compress(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_int2_compress(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_int2_compress(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_int2_consistent(internal, smallint, smallint, oid, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_int2_consistent(internal, smallint, smallint, oid, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_int2_consistent(internal, smallint, smallint, oid, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_int2_distance(internal, smallint, smallint, oid, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_int2_distance(internal, smallint, smallint, oid, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_int2_distance(internal, smallint, smallint, oid, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_int2_fetch(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_int2_fetch(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_int2_fetch(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_int2_penalty(internal, internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_int2_penalty(internal, internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_int2_penalty(internal, internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_int2_picksplit(internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_int2_picksplit(internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_int2_picksplit(internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_int2_same(gbtreekey4, gbtreekey4, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_int2_same(gbtreekey4, gbtreekey4, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_int2_same(gbtreekey4, gbtreekey4, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_int2_union(internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_int2_union(internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_int2_union(internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_int4_compress(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_int4_compress(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_int4_compress(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_int4_consistent(internal, integer, smallint, oid, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_int4_consistent(internal, integer, smallint, oid, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_int4_consistent(internal, integer, smallint, oid, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_int4_distance(internal, integer, smallint, oid, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_int4_distance(internal, integer, smallint, oid, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_int4_distance(internal, integer, smallint, oid, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_int4_fetch(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_int4_fetch(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_int4_fetch(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_int4_penalty(internal, internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_int4_penalty(internal, internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_int4_penalty(internal, internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_int4_picksplit(internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_int4_picksplit(internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_int4_picksplit(internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_int4_same(gbtreekey8, gbtreekey8, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_int4_same(gbtreekey8, gbtreekey8, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_int4_same(gbtreekey8, gbtreekey8, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_int4_union(internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_int4_union(internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_int4_union(internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_int8_compress(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_int8_compress(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_int8_compress(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_int8_consistent(internal, bigint, smallint, oid, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_int8_consistent(internal, bigint, smallint, oid, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_int8_consistent(internal, bigint, smallint, oid, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_int8_distance(internal, bigint, smallint, oid, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_int8_distance(internal, bigint, smallint, oid, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_int8_distance(internal, bigint, smallint, oid, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_int8_fetch(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_int8_fetch(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_int8_fetch(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_int8_penalty(internal, internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_int8_penalty(internal, internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_int8_penalty(internal, internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_int8_picksplit(internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_int8_picksplit(internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_int8_picksplit(internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_int8_same(gbtreekey16, gbtreekey16, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_int8_same(gbtreekey16, gbtreekey16, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_int8_same(gbtreekey16, gbtreekey16, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_int8_union(internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_int8_union(internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_int8_union(internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_intv_compress(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_intv_compress(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_intv_compress(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_intv_consistent(internal, interval, smallint, oid, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_intv_consistent(internal, interval, smallint, oid, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_intv_consistent(internal, interval, smallint, oid, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_intv_decompress(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_intv_decompress(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_intv_decompress(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_intv_distance(internal, interval, smallint, oid, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_intv_distance(internal, interval, smallint, oid, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_intv_distance(internal, interval, smallint, oid, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_intv_fetch(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_intv_fetch(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_intv_fetch(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_intv_penalty(internal, internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_intv_penalty(internal, internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_intv_penalty(internal, internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_intv_picksplit(internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_intv_picksplit(internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_intv_picksplit(internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_intv_same(gbtreekey32, gbtreekey32, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_intv_same(gbtreekey32, gbtreekey32, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_intv_same(gbtreekey32, gbtreekey32, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_intv_union(internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_intv_union(internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_intv_union(internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_macad8_compress(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_macad8_compress(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_macad8_compress(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_macad8_consistent(internal, macaddr8, smallint, oid, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_macad8_consistent(internal, macaddr8, smallint, oid, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_macad8_consistent(internal, macaddr8, smallint, oid, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_macad8_fetch(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_macad8_fetch(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_macad8_fetch(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_macad8_penalty(internal, internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_macad8_penalty(internal, internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_macad8_penalty(internal, internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_macad8_picksplit(internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_macad8_picksplit(internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_macad8_picksplit(internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_macad8_same(gbtreekey16, gbtreekey16, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_macad8_same(gbtreekey16, gbtreekey16, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_macad8_same(gbtreekey16, gbtreekey16, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_macad8_union(internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_macad8_union(internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_macad8_union(internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_macad_compress(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_macad_compress(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_macad_compress(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_macad_consistent(internal, macaddr, smallint, oid, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_macad_consistent(internal, macaddr, smallint, oid, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_macad_consistent(internal, macaddr, smallint, oid, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_macad_fetch(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_macad_fetch(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_macad_fetch(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_macad_penalty(internal, internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_macad_penalty(internal, internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_macad_penalty(internal, internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_macad_picksplit(internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_macad_picksplit(internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_macad_picksplit(internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_macad_same(gbtreekey16, gbtreekey16, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_macad_same(gbtreekey16, gbtreekey16, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_macad_same(gbtreekey16, gbtreekey16, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_macad_union(internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_macad_union(internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_macad_union(internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_numeric_compress(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_numeric_compress(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_numeric_compress(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_numeric_consistent(internal, numeric, smallint, oid, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_numeric_consistent(internal, numeric, smallint, oid, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_numeric_consistent(internal, numeric, smallint, oid, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_numeric_penalty(internal, internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_numeric_penalty(internal, internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_numeric_penalty(internal, internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_numeric_picksplit(internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_numeric_picksplit(internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_numeric_picksplit(internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_numeric_same(gbtreekey_var, gbtreekey_var, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_numeric_same(gbtreekey_var, gbtreekey_var, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_numeric_same(gbtreekey_var, gbtreekey_var, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_numeric_union(internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_numeric_union(internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_numeric_union(internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_oid_compress(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_oid_compress(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_oid_compress(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_oid_consistent(internal, oid, smallint, oid, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_oid_consistent(internal, oid, smallint, oid, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_oid_consistent(internal, oid, smallint, oid, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_oid_distance(internal, oid, smallint, oid, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_oid_distance(internal, oid, smallint, oid, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_oid_distance(internal, oid, smallint, oid, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_oid_fetch(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_oid_fetch(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_oid_fetch(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_oid_penalty(internal, internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_oid_penalty(internal, internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_oid_penalty(internal, internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_oid_picksplit(internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_oid_picksplit(internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_oid_picksplit(internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_oid_same(gbtreekey8, gbtreekey8, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_oid_same(gbtreekey8, gbtreekey8, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_oid_same(gbtreekey8, gbtreekey8, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_oid_union(internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_oid_union(internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_oid_union(internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_text_compress(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_text_compress(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_text_compress(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_text_consistent(internal, text, smallint, oid, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_text_consistent(internal, text, smallint, oid, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_text_consistent(internal, text, smallint, oid, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_text_penalty(internal, internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_text_penalty(internal, internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_text_penalty(internal, internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_text_picksplit(internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_text_picksplit(internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_text_picksplit(internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_text_same(gbtreekey_var, gbtreekey_var, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_text_same(gbtreekey_var, gbtreekey_var, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_text_same(gbtreekey_var, gbtreekey_var, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_text_union(internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_text_union(internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_text_union(internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_time_compress(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_time_compress(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_time_compress(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_time_consistent(internal, time without time zone, smallint, oid, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_time_consistent(internal, time without time zone, smallint, oid, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_time_consistent(internal, time without time zone, smallint, oid, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_time_distance(internal, time without time zone, smallint, oid, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_time_distance(internal, time without time zone, smallint, oid, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_time_distance(internal, time without time zone, smallint, oid, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_time_fetch(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_time_fetch(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_time_fetch(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_time_penalty(internal, internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_time_penalty(internal, internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_time_penalty(internal, internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_time_picksplit(internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_time_picksplit(internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_time_picksplit(internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_time_same(gbtreekey16, gbtreekey16, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_time_same(gbtreekey16, gbtreekey16, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_time_same(gbtreekey16, gbtreekey16, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_time_union(internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_time_union(internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_time_union(internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_timetz_compress(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_timetz_compress(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_timetz_compress(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_timetz_consistent(internal, time with time zone, smallint, oid, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_timetz_consistent(internal, time with time zone, smallint, oid, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_timetz_consistent(internal, time with time zone, smallint, oid, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_ts_compress(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_ts_compress(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_ts_compress(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_ts_consistent(internal, timestamp without time zone, smallint, oid, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_ts_consistent(internal, timestamp without time zone, smallint, oid, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_ts_consistent(internal, timestamp without time zone, smallint, oid, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_ts_distance(internal, timestamp without time zone, smallint, oid, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_ts_distance(internal, timestamp without time zone, smallint, oid, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_ts_distance(internal, timestamp without time zone, smallint, oid, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_ts_fetch(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_ts_fetch(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_ts_fetch(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_ts_penalty(internal, internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_ts_penalty(internal, internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_ts_penalty(internal, internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_ts_picksplit(internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_ts_picksplit(internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_ts_picksplit(internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_ts_same(gbtreekey16, gbtreekey16, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_ts_same(gbtreekey16, gbtreekey16, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_ts_same(gbtreekey16, gbtreekey16, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_ts_union(internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_ts_union(internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_ts_union(internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_tstz_compress(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_tstz_compress(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_tstz_compress(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_tstz_consistent(internal, timestamp with time zone, smallint, oid, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_tstz_consistent(internal, timestamp with time zone, smallint, oid, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_tstz_consistent(internal, timestamp with time zone, smallint, oid, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_tstz_distance(internal, timestamp with time zone, smallint, oid, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_tstz_distance(internal, timestamp with time zone, smallint, oid, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_tstz_distance(internal, timestamp with time zone, smallint, oid, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_uuid_compress(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_uuid_compress(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_uuid_compress(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_uuid_consistent(internal, uuid, smallint, oid, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_uuid_consistent(internal, uuid, smallint, oid, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_uuid_consistent(internal, uuid, smallint, oid, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_uuid_fetch(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_uuid_fetch(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_uuid_fetch(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_uuid_penalty(internal, internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_uuid_penalty(internal, internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_uuid_penalty(internal, internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_uuid_picksplit(internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_uuid_picksplit(internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_uuid_picksplit(internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_uuid_same(gbtreekey32, gbtreekey32, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_uuid_same(gbtreekey32, gbtreekey32, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_uuid_same(gbtreekey32, gbtreekey32, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_uuid_union(internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_uuid_union(internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_uuid_union(internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_var_decompress(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_var_decompress(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_var_decompress(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbt_var_fetch(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbt_var_fetch(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbt_var_fetch(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbtreekey16_in(cstring) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbtreekey16_in(cstring) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbtreekey16_in(cstring) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbtreekey16_out(gbtreekey16) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbtreekey16_out(gbtreekey16) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbtreekey16_out(gbtreekey16) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbtreekey2_in(cstring) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbtreekey2_in(cstring) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbtreekey2_in(cstring) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbtreekey2_out(gbtreekey2) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbtreekey2_out(gbtreekey2) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbtreekey2_out(gbtreekey2) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbtreekey32_in(cstring) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbtreekey32_in(cstring) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbtreekey32_in(cstring) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbtreekey32_out(gbtreekey32) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbtreekey32_out(gbtreekey32) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbtreekey32_out(gbtreekey32) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbtreekey4_in(cstring) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbtreekey4_in(cstring) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbtreekey4_in(cstring) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbtreekey4_out(gbtreekey4) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbtreekey4_out(gbtreekey4) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbtreekey4_out(gbtreekey4) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbtreekey8_in(cstring) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbtreekey8_in(cstring) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbtreekey8_in(cstring) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbtreekey8_out(gbtreekey8) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbtreekey8_out(gbtreekey8) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbtreekey8_out(gbtreekey8) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbtreekey_var_in(cstring) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbtreekey_var_in(cstring) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbtreekey_var_in(cstring) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gbtreekey_var_out(gbtreekey_var) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gbtreekey_var_out(gbtreekey_var) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gbtreekey_var_out(gbtreekey_var) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.generate_event_slug() FROM anon;
REVOKE EXECUTE ON FUNCTION public.generate_event_slug() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.generate_event_slug() FROM service_role;
REVOKE EXECUTE ON FUNCTION public.generate_invoice_reference() FROM anon;
REVOKE EXECUTE ON FUNCTION public.generate_invoice_reference() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.generate_invoice_reference() FROM service_role;
REVOKE EXECUTE ON FUNCTION public.generate_order_reference() FROM anon;
REVOKE EXECUTE ON FUNCTION public.generate_order_reference() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.generate_order_reference() FROM service_role;
REVOKE EXECUTE ON FUNCTION public.generate_reference_code() FROM anon;
REVOKE EXECUTE ON FUNCTION public.generate_reference_code() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.generate_reference_code() FROM service_role;
REVOKE EXECUTE ON FUNCTION public.generate_reservation_reference() FROM anon;
REVOKE EXECUTE ON FUNCTION public.generate_reservation_reference() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.generate_reservation_reference() FROM service_role;
REVOKE EXECUTE ON FUNCTION public.get_business_revenue(p_business_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_effective_config(p_at timestamp with time zone) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_effective_config(p_at timestamp with time zone) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.get_effective_config(p_at timestamp with time zone) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.get_order_revenue(p_business_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_outstanding_invoices(p_business_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gin_extract_query_trgm(text, internal, smallint, internal, internal, internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gin_extract_query_trgm(text, internal, smallint, internal, internal, internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gin_extract_query_trgm(text, internal, smallint, internal, internal, internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gin_extract_value_trgm(text, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gin_extract_value_trgm(text, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gin_extract_value_trgm(text, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gin_trgm_consistent(internal, smallint, text, integer, internal, internal, internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gin_trgm_consistent(internal, smallint, text, integer, internal, internal, internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gin_trgm_consistent(internal, smallint, text, integer, internal, internal, internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gin_trgm_triconsistent(internal, smallint, text, integer, internal, internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gin_trgm_triconsistent(internal, smallint, text, integer, internal, internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gin_trgm_triconsistent(internal, smallint, text, integer, internal, internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gtrgm_compress(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gtrgm_compress(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gtrgm_compress(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gtrgm_consistent(internal, text, smallint, oid, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gtrgm_consistent(internal, text, smallint, oid, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gtrgm_consistent(internal, text, smallint, oid, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gtrgm_decompress(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gtrgm_decompress(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gtrgm_decompress(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gtrgm_distance(internal, text, smallint, oid, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gtrgm_distance(internal, text, smallint, oid, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gtrgm_distance(internal, text, smallint, oid, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gtrgm_in(cstring) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gtrgm_in(cstring) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gtrgm_in(cstring) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gtrgm_options(internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gtrgm_options(internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gtrgm_options(internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gtrgm_out(gtrgm) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gtrgm_out(gtrgm) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gtrgm_out(gtrgm) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gtrgm_penalty(internal, internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gtrgm_penalty(internal, internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gtrgm_penalty(internal, internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gtrgm_picksplit(internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gtrgm_picksplit(internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gtrgm_picksplit(internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gtrgm_same(gtrgm, gtrgm, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gtrgm_same(gtrgm, gtrgm, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gtrgm_same(gtrgm, gtrgm, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.gtrgm_union(internal, internal) FROM anon;
REVOKE EXECUTE ON FUNCTION public.gtrgm_union(internal, internal) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.gtrgm_union(internal, internal) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.guard_commercial_settings() FROM anon;
REVOKE EXECUTE ON FUNCTION public.guard_commercial_settings() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.guard_commercial_settings() FROM service_role;
REVOKE EXECUTE ON FUNCTION public.guard_config_version_insert() FROM anon;
REVOKE EXECUTE ON FUNCTION public.guard_config_version_insert() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.guard_config_version_insert() FROM service_role;
REVOKE EXECUTE ON FUNCTION public.guard_country_activation() FROM anon;
REVOKE EXECUTE ON FUNCTION public.guard_country_activation() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.guard_country_activation() FROM service_role;
REVOKE EXECUTE ON FUNCTION public.guard_country_deletion() FROM anon;
REVOKE EXECUTE ON FUNCTION public.guard_country_deletion() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.guard_country_deletion() FROM service_role;
REVOKE EXECUTE ON FUNCTION public.guard_fee_policy_immutability() FROM anon;
REVOKE EXECUTE ON FUNCTION public.guard_fee_policy_immutability() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.guard_fee_policy_immutability() FROM service_role;
REVOKE EXECUTE ON FUNCTION public.guard_messaging_suspended() FROM anon;
REVOKE EXECUTE ON FUNCTION public.guard_messaging_suspended() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.guard_messaging_suspended() FROM service_role;
REVOKE EXECUTE ON FUNCTION public.guard_paystack_plan_code_authority() FROM anon;
REVOKE EXECUTE ON FUNCTION public.guard_paystack_plan_code_authority() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.guard_paystack_plan_code_authority() FROM service_role;
REVOKE EXECUTE ON FUNCTION public.guard_prize_instructions_integrity() FROM anon;
REVOKE EXECUTE ON FUNCTION public.guard_prize_instructions_integrity() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.guard_prize_instructions_integrity() FROM service_role;
REVOKE EXECUTE ON FUNCTION public.guard_provider_ref_authority() FROM anon;
REVOKE EXECUTE ON FUNCTION public.guard_provider_ref_authority() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.guard_provider_ref_authority() FROM service_role;
REVOKE EXECUTE ON FUNCTION public.guard_sending_requires_valid_reservation() FROM anon;
REVOKE EXECUTE ON FUNCTION public.guard_sending_requires_valid_reservation() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.guard_sending_requires_valid_reservation() FROM service_role;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM anon;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM service_role;
REVOKE EXECUTE ON FUNCTION public.handle_site_pages_updated_at() FROM anon;
REVOKE EXECUTE ON FUNCTION public.handle_site_pages_updated_at() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.handle_site_pages_updated_at() FROM service_role;
REVOKE EXECUTE ON FUNCTION public.int2_dist(smallint, smallint) FROM anon;
REVOKE EXECUTE ON FUNCTION public.int2_dist(smallint, smallint) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.int2_dist(smallint, smallint) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.int4_dist(integer, integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.int4_dist(integer, integer) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.int4_dist(integer, integer) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.int8_dist(bigint, bigint) FROM anon;
REVOKE EXECUTE ON FUNCTION public.int8_dist(bigint, bigint) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.int8_dist(bigint, bigint) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.interval_dist(interval, interval) FROM anon;
REVOKE EXECUTE ON FUNCTION public.interval_dist(interval, interval) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.interval_dist(interval, interval) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.next_queue_number(biz_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.next_queue_number(biz_id uuid) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.next_queue_number(biz_id uuid) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.normalize_promo_keyword() FROM anon;
REVOKE EXECUTE ON FUNCTION public.normalize_promo_keyword() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.normalize_promo_keyword() FROM service_role;
REVOKE EXECUTE ON FUNCTION public.oid_dist(oid, oid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.oid_dist(oid, oid) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.oid_dist(oid, oid) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.prevent_allowance_event_mutation() FROM anon;
REVOKE EXECUTE ON FUNCTION public.prevent_allowance_event_mutation() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.prevent_allowance_event_mutation() FROM service_role;
REVOKE EXECUTE ON FUNCTION public.prevent_config_version_mutation() FROM anon;
REVOKE EXECUTE ON FUNCTION public.prevent_config_version_mutation() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.prevent_config_version_mutation() FROM service_role;
REVOKE EXECUTE ON FUNCTION public.prevent_cost_event_mutation() FROM anon;
REVOKE EXECUTE ON FUNCTION public.prevent_cost_event_mutation() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.prevent_cost_event_mutation() FROM service_role;
REVOKE EXECUTE ON FUNCTION public.prevent_reconciliation_log_mutation() FROM anon;
REVOKE EXECUTE ON FUNCTION public.prevent_reconciliation_log_mutation() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.prevent_reconciliation_log_mutation() FROM service_role;
REVOKE EXECUTE ON FUNCTION public.prevent_snapshot_version_downgrade() FROM anon;
REVOKE EXECUTE ON FUNCTION public.prevent_snapshot_version_downgrade() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.prevent_snapshot_version_downgrade() FROM service_role;
REVOKE EXECUTE ON FUNCTION public.prevent_suspension_audit_mutation() FROM anon;
REVOKE EXECUTE ON FUNCTION public.prevent_suspension_audit_mutation() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.prevent_suspension_audit_mutation() FROM service_role;
REVOKE EXECUTE ON FUNCTION public.prevent_tier_tampering() FROM anon;
REVOKE EXECUTE ON FUNCTION public.prevent_tier_tampering() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.prevent_tier_tampering() FROM service_role;
REVOKE EXECUTE ON FUNCTION public.protect_profiles_role() FROM service_role;
REVOKE EXECUTE ON FUNCTION public.protect_profiles_role_insert() FROM service_role;
REVOKE EXECUTE ON FUNCTION public.set_limit(real) FROM anon;
REVOKE EXECUTE ON FUNCTION public.set_limit(real) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.set_limit(real) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.show_limit() FROM anon;
REVOKE EXECUTE ON FUNCTION public.show_limit() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.show_limit() FROM service_role;
REVOKE EXECUTE ON FUNCTION public.show_trgm(text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.show_trgm(text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.show_trgm(text) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.similarity(text, text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.similarity(text, text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.similarity(text, text) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.similarity_dist(text, text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.similarity_dist(text, text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.similarity_dist(text, text) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.similarity_op(text, text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.similarity_op(text, text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.similarity_op(text, text) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.strict_word_similarity(text, text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.strict_word_similarity(text, text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.strict_word_similarity(text, text) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.strict_word_similarity_commutator_op(text, text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.strict_word_similarity_commutator_op(text, text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.strict_word_similarity_commutator_op(text, text) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.strict_word_similarity_dist_commutator_op(text, text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.strict_word_similarity_dist_commutator_op(text, text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.strict_word_similarity_dist_commutator_op(text, text) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.strict_word_similarity_dist_op(text, text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.strict_word_similarity_dist_op(text, text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.strict_word_similarity_dist_op(text, text) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.strict_word_similarity_op(text, text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.strict_word_similarity_op(text, text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.strict_word_similarity_op(text, text) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.sync_service_status_to_is_active() FROM anon;
REVOKE EXECUTE ON FUNCTION public.sync_service_status_to_is_active() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.sync_service_status_to_is_active() FROM service_role;
REVOKE EXECUTE ON FUNCTION public.time_dist(time without time zone, time without time zone) FROM anon;
REVOKE EXECUTE ON FUNCTION public.time_dist(time without time zone, time without time zone) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.time_dist(time without time zone, time without time zone) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.ts_dist(timestamp without time zone, timestamp without time zone) FROM anon;
REVOKE EXECUTE ON FUNCTION public.ts_dist(timestamp without time zone, timestamp without time zone) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.ts_dist(timestamp without time zone, timestamp without time zone) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.tstz_dist(timestamp with time zone, timestamp with time zone) FROM anon;
REVOKE EXECUTE ON FUNCTION public.tstz_dist(timestamp with time zone, timestamp with time zone) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.tstz_dist(timestamp with time zone, timestamp with time zone) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.update_business_rating() FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_business_rating() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.update_business_rating() FROM service_role;
REVOKE EXECUTE ON FUNCTION public.update_countries_updated_at() FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_countries_updated_at() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.update_countries_updated_at() FROM service_role;
REVOKE EXECUTE ON FUNCTION public.update_customer_subscriptions_updated_at() FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_customer_subscriptions_updated_at() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.update_customer_subscriptions_updated_at() FROM service_role;
REVOKE EXECUTE ON FUNCTION public.update_last_active_on_deactivate() FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_last_active_on_deactivate() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.update_last_active_on_deactivate() FROM service_role;
REVOKE EXECUTE ON FUNCTION public.update_promo_campaign_updated_at() FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_promo_campaign_updated_at() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.update_promo_campaign_updated_at() FROM service_role;
REVOKE EXECUTE ON FUNCTION public.update_updated_at() FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_updated_at() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.update_updated_at() FROM service_role;
REVOKE EXECUTE ON FUNCTION public.validate_allowance_event_tenant() FROM anon;
REVOKE EXECUTE ON FUNCTION public.validate_allowance_event_tenant() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.validate_allowance_event_tenant() FROM service_role;
REVOKE EXECUTE ON FUNCTION public.validate_fee_basis() FROM anon;
REVOKE EXECUTE ON FUNCTION public.validate_fee_basis() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.validate_fee_basis() FROM service_role;
REVOKE EXECUTE ON FUNCTION public.validate_promo_campaign_status_transition() FROM anon;
REVOKE EXECUTE ON FUNCTION public.validate_promo_campaign_status_transition() FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.validate_promo_campaign_status_transition() FROM service_role;
REVOKE EXECUTE ON FUNCTION public.word_similarity(text, text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.word_similarity(text, text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.word_similarity(text, text) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.word_similarity_commutator_op(text, text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.word_similarity_commutator_op(text, text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.word_similarity_commutator_op(text, text) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.word_similarity_dist_commutator_op(text, text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.word_similarity_dist_commutator_op(text, text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.word_similarity_dist_commutator_op(text, text) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.word_similarity_dist_op(text, text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.word_similarity_dist_op(text, text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.word_similarity_dist_op(text, text) FROM service_role;
REVOKE EXECUTE ON FUNCTION public.word_similarity_op(text, text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.word_similarity_op(text, text) FROM authenticated;
REVOKE EXECUTE ON FUNCTION public.word_similarity_op(text, text) FROM service_role;

COMMIT;
